
const mongoose = require('mongoose');
const Schema=mongoose.Schema;

const Review=require("./review.js");

const listingSchema = new Schema({
  title: { 
    type: String,
    required: true
},

description:{
    type:String,
},
image:{
    url:String,
    filename:String,
    //  type:String,
    //     default: "https://images.unsplash.com/photo-1720048169707-a32d6dfca0b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
    //     set:(v)=>
    //     v===" " 
    //      ? "https://images.unsplash.com/photo-1720048169707-a32d6dfca0b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8" 
    //     :v,
},
price: { 
type: Number,
    required: true 
},
location: {
    type:String
},
country: {
    type:String
},
reviews:[{
    type:Schema.Types.ObjectId,
    ref:"Reviews",
}],
owner:{
    type:Schema.Types.ObjectId,
    ref:"User",
},
geometry:{
    type: {
        type: String, // Don't do `{ location: { type: String } }`
        enum: ['Point'], // 'location.type' must be 'Point'
        required: true
      },
      coordinates: {
        type: [Number],
        required: true
      }
},
category:{
    type:String,
    enum:["mountains","arctic","farms","deserts"],
},

});

//  hamdling reviews delete.(mongoose middleware ).....

listingSchema.post("findOneAndDelete",async(listing)=>{
    if(listing){
        await Review.deleteMany({ _id:{$in:listing.reviews}});
    }
});


const Listing = mongoose.model('Listing', listingSchema);

module.exports = Listing;


//    shradha khapara code generated by ..........(this code my system error).........

// const mongoose=require("mongoose");
// const Schema=mongoose.Schema;

// const listingSChema= new Schema({
//     title:{
//         type:String,
//         required:true,
//     },
//     description:{
//         type:String,
//     },
    // image:{
    //    // type:String,
        // default: "https://images.unsplash.com/photo-1720048169707-a32d6dfca0b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
        // set:(v)=>
        // v===" " 
        //  ? "https://images.unsplash.com/photo-1720048169707-a32d6dfca0b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8" 
        // :v,

    // },
//     price:{
//         type:Number,
//     },
//     location:{
//         type:String,
//     },
//     country:{
//         type:String,
//     },

// });

// const Listing=mongoose.model("Listing",listingSChema);
// module.exports=Listing;


//  both code are difference .....................
